services:
  backend:
    build: ./backend
    container_name: quarkus-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
